# -*- coding: utf-8 -*-

CONFIG = {
    "model_name": "vit_base_patch16_224",
    "experiment_name": "vit_b16_300",
    "train_dir": "/food_data/food_data/CNFOOD-241/CNFOOD-241/train600x600",
    "val_dir": "/food_data/food_data/CNFOOD-241/CNFOOD-241/val600x600",
    "num_classes": 241,
    "img_size": 300,
    "pretrained": True,
    "batch_size": 128,
    "epochs": 30,
    "lr": 5e-5,
    "weight_decay": 0.05,
    "warmup_epochs": 5,
    "cosine_min_lr_ratio": 0.01,
    "label_smoothing": 0.1,
    "mixup_alpha": 0.2,
    "cutmix_alpha": 1.0,
    "random_erasing": True,
    "random_erasing_p": 0.25,
    "num_workers": 8,
    "prefetch_factor": 2,
    "pin_memory": True,
    "amp_dtype": "fp16",
    "channels_last": False,
    "dataparallel": True,
    "compile": False,
    "seed": 42,
    "eval_every": 1,
    "out_dir": "./exp_vit_b16_300",
}
